### ISSUE TITLE
howto contribute to documentation

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/tango-doc#231]
Page https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/tutorials/documentation-workflow-tutorial.html#sphinx-installation could be updated by replacing virtualenv by `python3 -m venv tango-doc` for example (see https://docs.python.org/3/tutorial/venv.html).

**Comment by PhilLAL** [comment]
Related to #232

**Comment by PhilLAL** [comment]
Perhaps a naming convention could be useful for tango-doc newcomers, for example for:
-Tango or TANGO or tango: it has been choosen to use Tango
-device server or Device Server or Device server (perhaps Device server only for explaining the concept)
-etc.

**Comment by PhilLAL** [comment]
Several pages contains some materials for contributing:
- https://tango-controls.readthedocs.io/en/dev/development/contributing/index.html
- https://tango-controls.readthedocs.io/en/dev/tutorials-and-howtos/tutorials/documentation-workflow-tutorial.html

Shouldn't we merge this into the same page?

**Comment by piogor** [comment]
@PhilLAL, these documents cross reference, so I am closing this. However, feel free to reopen the issue if you think it is important to have both in the same document. My consideration to keep it as two documents is because one is providing general rules and the other is a workflow tutorial or set of hints not a standard and someone may use another workflow.
