### ISSUE TITLE
Standardize default branches across tango projects

### ISSUE THREAD

**Issue by t-b** [tango-controls/tango-doc#255]
As discussed at the last kernel meeting in 2/2019.

I understand https://docs.readthedocs.io/en/latest/versions.html as that it uses as default branch name `master` for git and uses that for the development version.

So replacing dev with master should work. This also requires to change the default branch in github.

**Comment by piogor** [comment]
@t-b, thanks for the remainder. Previously, it was configured as you mention :-).
However, it is more to adopt a procedure with the master branch being a default git branch while keeping 'dev' branch as the one which is used to build on RtD  (following  #92). 
Anyway, I will discuss with @andygotz,  whether we revert #92 decision and go back to use 'latest' instead of 'dev'...

**Comment by Ingvord** [comment]
+1 to have `master` as default git/RtD branch. I think the `latest` on the RtD should be the _latest_ i.e. most recent version of the documentation. Sorry for my ignorance, but what is an intention behind #92 ?

**Comment by piogor** [comment]
As far as I remember, it was because the `latest` suggests specific (the latest) release while `dev` means transient between releases.
I do prefer using `master` and `latest`, too. This is why I was so reluctant to implement #92.

**Comment by piogor** [comment]
After talking to Andy, we are reversing #92. So the default branch is now set to 'master'.
