### ISSUE TITLE
Create a section with known-issues

### ISSUE THREAD

**Issue by mliszcz** [tango-controls/tango-doc#325]
Action defined in Kernel meeting held on 2020-04-09: https://github.com/tango-controls/tango-kernel-followup/blob/master/2020/2020-04-09/Minutes.md#status-of-actions-defined-in-the-previous-meetings:

> Create a section in the documentation listing the known work-arounds for known issues and things to avoid when programming with Tango. We agreed that S2Innovation will only create a placeholder for the moment for this section. Contributors will have to create Pull Requests to add content

**Comment by reszelaz** [comment]
Hi,

In the past we have created a similar section in the documentation of the Sardana project. I  remember we discussed a lot on how to make it as up to date as possible and we decided to create a dedicated label in GitHub and tag all issues that we would like to include in the list of known problems.
So, in our case it looks like [this](https://github.com/sardana-org/sardana/issues?q=is:issue+is:open+label:doc:knownbug) and in the docs we simply added the Known Problems item in the TOC of the [User's Guide](https://sardana-controls.org/users/index.html#) which points to the URL on GitHub. We also said to improve these issues' subjects so these are easy understandable to the users, add workaround in the issues' descriptions, etc. but as you will see it is not always done...

I see seveeral benefits of this approach:
* easy adding of problems to the list
* automatically removing them when eventually the problem is solved
* all the benefits of GitHub issues e.g. users can complement it with comments, links, etc.
* at least for me, markup editing/previewing is slightly easier then reStructuredText (then I have no excuses on not writing the docs:))

In case of Tango it may be difficult to follow this approach cause there are multiple GitHub projects in the organization. But maybe this could be solved by creating a label in all of them (or just starting with the most common ones like, cppTango, JTango, PyTango, etc.)  and then have a multiple sub-items in TOC. Another way could be to make these _known problem_ issues just in the TangoTickets project...

Also from the very short experience with this (we added this secion a year ago, or so) I always find a lot of doubts on when the issue is a known problem, or yet another of hundreds of issues...

Sorry to introduce noise on this.. for sure you have already discussed all these on the kernel follow-up meeting.
Have a nice weekend!
Zibi

**Comment by mliszcz** [comment]
Hi Zibi,

Thanks a lot for your input. Having this list generated automatically like Sardana does is definitely good idea, but the intention here was to document the issues that simply cannot be fixed due to the current SW design (i.e. fixing them may require significant API changes). This topic came up after user tried to push event from read callback after calling set_value. On the kernel meeting we decided that for now we will update this list via PRs.

We also have a 'bug' label in cppTango, but we usually just try to resolve them if possible. Still, it would be interesting to hear what is the difference between 'bug' and 'doc:knownbug' in Sardana and why these two does not always come together. Thanks in advance!

CC @bourtemb

**Comment by reszelaz** [comment]
Thanks for the explanation Michal!

The example which you bring could be tagged as _knownproblem_ & _wontfix_ and then one could fine tune the GitHub search to obtain the list. Also, maybe it makes some sense to add to this list issues which are planed to be fixed but in longer term?

In Sardana project we have a very long backlog of issues, part of them is related to the Sardana usability, some to the performance, others to the test suite, others to documentation, we also use it as a channel to ask questions, etc. With the list of _known problems_ we try to give more visibility to certain issues which when found early by the users could avoid problems hard to debug in the future, make them aware of some limitations, etc. So, it is kind of filterted view of the backlog. This was our intention when we were creating it. And as I mentioned, at least to me, it is always difficult to decide if this issue _deserves_ to be on the list...

Now, I don't remember why we used the "doc:knownbug" label and not "doc:knownproblem" which I think would be better, but this is not so important and can be renamed. In the docs we called the section "Known problems" and in the label description use the same name.
