### ISSUE TITLE
Add checking external links to Travis.

### ISSUE THREAD

**Issue by LJBD** [tango-controls/tango-doc#67]
Since there are many external links that might be broken, we should check them during building.
It seems that one just has to run `sphinx-build -b linkcheck` (as it's described [here](http://www.sphinx-doc.org/en/stable/invocation.html#invocation-of-sphinx-build)).

**Comment by Ingvord** [comment]
Looks like this fails randomly in CI due to `The command "sphinx-build -b linkcheck source build" exited with 1`

As results of the CI must be consistent and reproducible IMHO we should remove this and instead add to the contribution guideline i.e. ask contributor/maintainer to manually check links before merging.

**Comment by piogor** [comment]
Since, some time the Travis does not report false fails. I think we may close the task. In case of later troubles we may create new one to fine tune the checking mechanism.
